name: movie_finder
description: "Movie Finder APP"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.1
  flutter_riverpod: ^2.5.1
  cupertino_icons: ^1.0.8
  share_plus: ^9.0.0
  sqflite: ^2.3.3
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/